# Site settings
title: 'A Puzzling Proposal' # Your Title
tagline: 'An extremely elaborate plot for tricking Melissa into marrying me.' # A brief tagline for your site
sidebar_image: /images/cover.jpg

baseurl: /proposal # the subpath of your site, e.g. /blog/
